services:
  # Service MongoDB
  mongodb:
    image: mongo:7.0
    container_name: grammachat-mongodb
    restart: unless-stopped
    ports:
      - "${MONGODB_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - grammachat-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service Redis
  redis:
    image: redis:7.2-alpine
    container_name: grammachat-redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - grammachat-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Service API Express.js
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: grammachat-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${API_PORT:-3000}
      MONGODB_URI: ${MONGODB_URI:-mongodb://mongodb:27017/grammachat}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      LANGUAGETOOL_API_URL: ${LANGUAGETOOL_API_URL:-https://api.languagetool.org/v2/check}
      LANGUAGETOOL_API_KEY: ${LANGUAGETOOL_API_KEY:-}
      XP_PER_CHARACTER: ${XP_PER_CHARACTER:-1}
      XP_BONUS_NO_ERRORS: ${XP_BONUS_NO_ERRORS:-10}
      XP_PENALTY_PER_ERROR: ${XP_PENALTY_PER_ERROR:-5}
      LEVEL_UP_THRESHOLD: ${LEVEL_UP_THRESHOLD:-100}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000,http://localhost:19006}
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - grammachat-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  grammachat-network:
    driver: bridge